# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# Spring配置
spring:
  application:
    name: remote-sensing-web
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rs_analysis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: cxz20030620
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rs.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# 自定义配置
rs:
  # 文件存储路径
  file-storage:
    base-path: D:/Code/System/remote-sensing-web-simple/remote-sensing-web-simple/file_store
    remote-image-path: ${rs.file-storage.base-path}/remote-image
  # 算法服务配置
  algorithm:
    url: http://localhost:5000
  # 文件服务配置
  file-service:
    url: http://localhost:5001